default_context:
  project_name: 'sistema_alerta_academica'
  project_slug: 'dev'
  domain_main: 'sistema-alerta-academica'
  domain_staging: 'stag.sistema-alerta-academica'
  docker_swarm_stack_name_main: 'sistema-alerta-academica'
  docker_swarm_stack_name_staging: 'stag-sistema-alerta-academica'
  secret_key: '6d81abd696fcd735861c0a1ded7a6212c584fd3099c8264e760948ab4589264a'
  first_superuser: 'admin'
  first_superuser_password: 'kike2311'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.sistema-alerta-academica", "https://stag.sistema-alerta-academica", "https://sistema-alerta-academica", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@sistema-alerta-academica.com'
  postgres_password: 'kike2311'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'kike2311'
  traefik_constraint_tag: 'sistema-alerta-academica'
  traefik_constraint_tag_staging: 'stag.sistema-alerta-academica'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:kike2311'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
