"""column grades nullable

Revision ID: 60038c04a8b3
Revises: a86751f23d95
Create Date: 2023-12-21 03:58:20.755183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60038c04a8b3'
down_revision = 'a86751f23d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
